### ISSUE TITLE
bools in openvr_capi.h should map to std::os::raw::c_char on windows

### ISSUE THREAD

**Issue by jaredr** [rust-openvr/rust-openvr-sys#1]
`openvr_capi.h` contains:

```
#if defined( __WIN32 )
typedef char bool;
#endif
```

but `scripts/binding.h` contains:

```
#define bool int
```

I think this causes bindgen to map `bool`s to `std::os::raw::c_int`s which creates problems for some structs on Windows.

For example `sizeof(TrackedDevicePose_t)` is 80 bytes in C, but `std::mem::size_of::<openvr_sys::TrackedDevicePose_t>()` is 84 bytes in Rust. (This case is particularly sneaky as `WaitGetPoses` provides an array of these where the zeroth element is mostly correct, but each subsequent element gets shifted further.)

Mapping `bool` to `std::os::raw::c_char` on Windows in accordance with the header typedef fixes the problem.

**Comment by reneeichhorn** [comment]
Oh yes, that's right! If I remember correctly bindgen also has some options related too booleans. I will check it tomorrow. Thanks for your feedback!

**Comment by carlosdp** [comment]
Was this fixed? I think I might be running into this on Windows, the values on the tracked devices seem all messed up, with some devices that are of type Invalid being marked as valid or connected, and no devices having both is_valid and is_connected set.

**Comment by jaredr** [comment]
For a quick workaround, you can just hack up your openvr_sys lib.rs file:

```
#[repr(C)]
#[derive(Copy, Clone)]
#[derive(Debug)]
pub struct TrackedDevicePose_t {
    pub mDeviceToAbsoluteTracking: HmdMatrix34_t,
    pub vVelocity: HmdVector3_t,
    pub vAngularVelocity: HmdVector3_t,
    pub eTrackingResult: ETrackingResult,
    pub bPoseIsValid: ::std::os::raw::c_char,        // HERE!
    pub bDeviceIsConnected: ::std::os::raw::c_char,  // AND HERE!
}
```

If you're using cargo to pull in openvr_sys, it'll be somewhere weird like: `%HOME%\.cargo\registry\src\github.com-[somethingweird]\openvr_sys-1.0.2`. And you'll probably have to run `cargo clean -p openvr_sys` to make sure it gets rebuilt. Also, I think there are other structures that this issue affects, but I haven't run into them yet.

**Comment by carlosdp** [comment]
Yea that's what I ended up doing, just made my own fork and manually fixed it in as many places as I could find =P Thanks!

**Comment by reneeichhorn** [comment]
@carlosdp can you report that the fix is all required? Or did you find other type incompatibilities?

**Comment by carlosdp** [comment]
The only one I've found is this bool type mismatch. Bools need to be `c_int` or the data is read at incorrect offsets.

**Comment by Ralith** [comment]
It seems that this issue has gone unfixed. Is this library maintained?

**Comment by reneeichhorn** [comment]
Hey guys, sorry for the late response, I've been very busy lately.
I'm currently not really maintaining the library to be honest. I very open for new contributors that want the join the rust-openvr family though. I reserved some time for tomorrow to check the PR for the new version, and see if that already fixes the bool issues.

**Comment by Ralith** [comment]
I believe this was mooted by #4. The library is currently working on Windows for me. Feel free to reopen if I've missed something.
